steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dubhacks2020:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dubhacks2020:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/dubhacks2020:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/dubhacks2020:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dubhacks2020:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'dubhacks2020'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dubhacks2020:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/dubhacks2020:$COMMIT_SHA'
